name: CI to npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            node_modules
            usr/**/node_modules
          key: ${{ runner.os }}-node_modules-${{hashFiles('**/package.json')}}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

      - name: Build lib
        run: npm run build
        
      - uses: JS-Devtools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}